@startuml
class Task{
- fatherProject
- intervals[]
+ sumIntervals()
+ finishTask()
+ setInterval()
+ getFatherProject()
}
class Project{
- nameProject
+ getInfoTask()
+ timeProject
+ getSumaTask()
+ setTask()
}
class Interval{
- dateStart
- dateFinal
- duration
+ calculateTotalTime()
+ getDate()
+ update()
+ timeBetweenUpdates()
}
abstract Activity{
- dateStart
- dateFinal
+ getFather()
}

class Clock{
}

package Observer/Observable <<Folder>> {
interface Observer{
}
abstract Observable{
}
}


Project *-- "1..*" Activity
Project  -up-|> Activity
Task -up-|> Activity
Clock --|> Observable
Task *-- "0..*" Interval
Interval ..|> Observer



@enduml